import type { Service } from '@/types'

export const mockServices: Service[] = [
  {
    id: 's1',
    creator_id: 'c1',
    title: 'Custom Logo & Brand Identity',
    slug: 'custom-logo-brand-identity',
    description: 'I will design a unique, memorable logo and brand identity system for your product or startup. Includes logo mark, wordmark, color palette, and typography guidelines. Perfect for indie developers launching a new product or creators building their personal brand.',
    short_desc: 'Unique logo and brand identity for your product or startup.',
    category: 'design',
    cover_url: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800&q=80',
    delivery_time_days: 7,
    published: true,
    created_at: new Date().toISOString(),
    tiers: [
      {
        id: 'st1a', service_id: 's1', name: 'basic', title: 'Logo Only',
        description: 'One logo concept with 2 revisions.',
        price_cents: 4900, delivery_time_days: 5, revisions: 2,
        features: ['1 logo concept', 'PNG + SVG files', '2 revisions'],
      },
      {
        id: 'st1b', service_id: 's1', name: 'standard', title: 'Logo + Brand Kit',
        description: 'Two logo concepts with full brand kit.',
        price_cents: 9900, delivery_time_days: 7, revisions: 4,
        features: ['2 logo concepts', 'PNG + SVG + AI files', 'Color palette', 'Typography guide', '4 revisions'],
      },
      {
        id: 'st1c', service_id: 's1', name: 'premium', title: 'Full Identity System',
        description: 'Complete brand identity with social templates.',
        price_cents: 19900, delivery_time_days: 14, revisions: 8,
        features: ['3 logo concepts', 'All source files', 'Brand guidelines PDF', 'Social media templates', 'Business card design', '8 revisions'],
      },
    ],
    creator: {
      id: 'c1', user_id: 'u1', username: 'elena-design', display_name: 'Elena Vasquez',
      bio: 'Brand designer with 8 years of experience.', avatar_url: null,
      website: null, twitter: null, total_products: 3, total_sales: 45, created_at: new Date().toISOString(),
    },
  },
  {
    id: 's2',
    creator_id: 'c2',
    title: 'React Component Development',
    slug: 'react-component-development',
    description: 'I will build production-ready React components with TypeScript, proper accessibility, and full test coverage. Specializing in complex UI: data tables, drag-and-drop interfaces, form builders, and animation-heavy components.',
    short_desc: 'Production-ready React + TypeScript components with tests.',
    category: 'dev',
    cover_url: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80',
    delivery_time_days: 5,
    published: true,
    created_at: new Date().toISOString(),
    tiers: [
      {
        id: 'st2a', service_id: 's2', name: 'basic', title: 'Single Component',
        description: 'One React component with TypeScript.',
        price_cents: 7500, delivery_time_days: 3, revisions: 2,
        features: ['1 component', 'TypeScript', 'Basic tests', '2 revisions'],
      },
      {
        id: 'st2b', service_id: 's2', name: 'standard', title: 'Component Suite',
        description: 'Up to 3 related components with full tests.',
        price_cents: 15000, delivery_time_days: 7, revisions: 4,
        features: ['Up to 3 components', 'TypeScript', 'Full test coverage', 'Storybook stories', 'A11y compliant', '4 revisions'],
      },
      {
        id: 'st2c', service_id: 's2', name: 'premium', title: 'Full Feature Module',
        description: 'Complete feature module with API integration.',
        price_cents: 30000, delivery_time_days: 14, revisions: 6,
        features: ['Full feature module', 'API integration', 'State management', 'E2E tests', 'Documentation', 'Code review walkthrough', '6 revisions'],
      },
    ],
    creator: {
      id: 'c2', user_id: 'u2', username: 'kai-dev', display_name: 'Kai Nakamura',
      bio: 'Senior frontend engineer. React specialist.', avatar_url: null,
      website: null, twitter: null, total_products: 2, total_sales: 31, created_at: new Date().toISOString(),
    },
  },
  {
    id: 's3',
    creator_id: 'c3',
    title: 'UI/UX Audit & Redesign',
    slug: 'ui-ux-audit-redesign',
    description: 'I will review your existing product and provide a detailed UX audit with actionable recommendations, annotated screenshots, and optional redesign mockups. I focus on conversion optimization, accessibility, and modern design patterns.',
    short_desc: 'Detailed UX audit with redesign mockups for your product.',
    category: 'consulting',
    cover_url: 'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=800&q=80',
    delivery_time_days: 5,
    published: true,
    created_at: new Date().toISOString(),
    tiers: [
      {
        id: 'st3a', service_id: 's3', name: 'basic', title: 'Quick Audit',
        description: 'Written UX review with top 10 issues.',
        price_cents: 5900, delivery_time_days: 3, revisions: 1,
        features: ['Up to 5 pages reviewed', 'Top 10 issues report', 'Priority matrix', '1 revision'],
      },
      {
        id: 'st3b', service_id: 's3', name: 'standard', title: 'Full Audit',
        description: 'Comprehensive audit with annotated screenshots.',
        price_cents: 12900, delivery_time_days: 7, revisions: 2,
        features: ['Full app review', 'Annotated screenshots', 'Competitor analysis', 'A11y checklist', '30-min video walkthrough', '2 revisions'],
      },
      {
        id: 'st3c', service_id: 's3', name: 'premium', title: 'Audit + Redesign',
        description: 'Full audit plus hi-fi redesign mockups.',
        price_cents: 24900, delivery_time_days: 14, revisions: 4,
        features: ['Everything in Full Audit', 'Hi-fi redesign (up to 5 screens)', 'Interactive prototype', 'Design system tokens', 'Handoff-ready Figma file', '4 revisions'],
      },
    ],
    creator: {
      id: 'c3', user_id: 'u3', username: 'sam-ux', display_name: 'Sam Torres',
      bio: 'Product designer focused on developer tools.', avatar_url: null,
      website: null, twitter: null, total_products: 1, total_sales: 22, created_at: new Date().toISOString(),
    },
  },
  {
    id: 's4',
    creator_id: 'c1',
    title: 'Custom Illustration Pack',
    slug: 'custom-illustration-pack',
    description: 'Hand-drawn digital illustrations tailored to your brand. Perfect for landing pages, onboarding flows, and marketing materials. I work in a modern, minimal style with subtle texture.',
    short_desc: 'Custom hand-drawn illustrations for your brand.',
    category: 'design',
    cover_url: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&q=80',
    delivery_time_days: 10,
    published: true,
    created_at: new Date().toISOString(),
    tiers: [
      {
        id: 'st4a', service_id: 's4', name: 'basic', title: '3 Illustrations',
        description: 'Three spot illustrations.',
        price_cents: 8900, delivery_time_days: 7, revisions: 2,
        features: ['3 illustrations', 'PNG + SVG', 'One art style', '2 revisions'],
      },
      {
        id: 'st4b', service_id: 's4', name: 'standard', title: '6 Illustrations',
        description: 'Six illustrations with consistent style.',
        price_cents: 15900, delivery_time_days: 10, revisions: 3,
        features: ['6 illustrations', 'All source files', 'Consistent style guide', 'Light + dark variants', '3 revisions'],
      },
      {
        id: 'st4c', service_id: 's4', name: 'premium', title: '12 Illustrations',
        description: 'Full illustration system.',
        price_cents: 27900, delivery_time_days: 18, revisions: 5,
        features: ['12 illustrations', 'All source files', 'Animation-ready layers', 'Style guide document', 'Icon companions', '5 revisions'],
      },
    ],
    creator: {
      id: 'c1', user_id: 'u1', username: 'elena-design', display_name: 'Elena Vasquez',
      bio: 'Brand designer with 8 years of experience.', avatar_url: null,
      website: null, twitter: null, total_products: 3, total_sales: 45, created_at: new Date().toISOString(),
    },
  },
]
