import type { ShowcasePost } from '@/types'

export const mockShowcase: ShowcasePost[] = [
  {
    id: 'sh1',
    creator_id: 'c1',
    caption: 'New brand identity for a fintech startup. Explored organic shapes to balance the corporate feel.',
    tags: ['branding', 'logo-design', 'fintech'],
    published: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    media: [{ id: 'm1', post_id: 'sh1', media_url: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=600&q=80', media_type: 'image', width: 600, height: 450, sort_order: 0 }],
    creator: { id: 'c1', user_id: 'u1', username: 'elena-design', display_name: 'Elena Vasquez', bio: null, avatar_url: null, website: null, twitter: null, total_products: 3, total_sales: 45, created_at: '' },
    like_count: 24,
    liked_by_user: false,
  },
  {
    id: 'sh2',
    creator_id: 'c2',
    caption: 'Built a custom drag-and-drop kanban board with React DnD. Smooth animations and accessible keyboard nav.',
    tags: ['react', 'frontend', 'open-source'],
    published: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    media: [{ id: 'm2', post_id: 'sh2', media_url: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&q=80', media_type: 'image', width: 600, height: 400, sort_order: 0 }],
    creator: { id: 'c2', user_id: 'u2', username: 'kai-dev', display_name: 'Kai Nakamura', bio: null, avatar_url: null, website: null, twitter: null, total_products: 2, total_sales: 31, created_at: '' },
    like_count: 42,
    liked_by_user: false,
  },
  {
    id: 'sh3',
    creator_id: 'c3',
    caption: 'Dashboard redesign for a developer tools company. Focus on information density without sacrificing clarity.',
    tags: ['ui-design', 'dashboard', 'dev-tools'],
    published: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    media: [{ id: 'm3', post_id: 'sh3', media_url: 'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=600&q=80', media_type: 'image', width: 600, height: 380, sort_order: 0 }],
    creator: { id: 'c3', user_id: 'u3', username: 'sam-ux', display_name: 'Sam Torres', bio: null, avatar_url: null, website: null, twitter: null, total_products: 1, total_sales: 22, created_at: '' },
    like_count: 18,
    liked_by_user: false,
  },
  {
    id: 'sh4',
    creator_id: 'c1',
    caption: 'Illustration series for a meditation app. Watercolor textures on digital canvas.',
    tags: ['illustration', 'app-design', 'wellness'],
    published: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    media: [{ id: 'm4', post_id: 'sh4', media_url: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&q=80', media_type: 'image', width: 600, height: 600, sort_order: 0 }],
    creator: { id: 'c1', user_id: 'u1', username: 'elena-design', display_name: 'Elena Vasquez', bio: null, avatar_url: null, website: null, twitter: null, total_products: 3, total_sales: 45, created_at: '' },
    like_count: 37,
    liked_by_user: false,
  },
  {
    id: 'sh5',
    creator_id: 'c2',
    caption: 'Terminal-based portfolio website. Built with Next.js, renders as an interactive CLI.',
    tags: ['frontend', 'nextjs', 'creative-coding'],
    published: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    media: [{ id: 'm5', post_id: 'sh5', media_url: 'https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=600&q=80', media_type: 'image', width: 600, height: 340, sort_order: 0 }],
    creator: { id: 'c2', user_id: 'u2', username: 'kai-dev', display_name: 'Kai Nakamura', bio: null, avatar_url: null, website: null, twitter: null, total_products: 2, total_sales: 31, created_at: '' },
    like_count: 56,
    liked_by_user: false,
  },
  {
    id: 'sh6',
    creator_id: 'c3',
    caption: 'Mobile app concept for a plant care tracker. Soft greens, playful micro-interactions.',
    tags: ['mobile', 'ui-design', 'concept'],
    published: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
    media: [{ id: 'm6', post_id: 'sh6', media_url: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&q=80', media_type: 'image', width: 600, height: 500, sort_order: 0 }],
    creator: { id: 'c3', user_id: 'u3', username: 'sam-ux', display_name: 'Sam Torres', bio: null, avatar_url: null, website: null, twitter: null, total_products: 1, total_sales: 22, created_at: '' },
    like_count: 29,
    liked_by_user: false,
  },
]
