import { ProductPublic } from '@/types'

export const mockProducts: ProductPublic[] = [
  {
    id: '1',
    title: 'Slate UI Kit',
    slug: 'slate-ui-kit',
    description: 'A comprehensive dark-mode UI kit with 120+ components built for Figma. Includes design tokens, auto-layout frames, and a full component library ready for production use.',
    short_desc: '120+ dark-mode Figma components with design tokens.',
    category: 'design',
    price_cents: 2900,
    is_free: false,
    cover_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80',
    file_count: 3,
    published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Next.js Starter',
    slug: 'nextjs-starter',
    description: 'Production-ready Next.js 14 starter with TypeScript, Tailwind, authentication, and database setup. Save hours of boilerplate and ship faster.',
    short_desc: 'Production Next.js 14 + TypeScript + Tailwind starter.',
    category: 'dev',
    price_cents: 1900,
    is_free: false,
    cover_url: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80',
    file_count: 1,
    published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Icon Pack — Forest',
    slug: 'icon-pack-forest',
    description: 'A free set of 48 hand-crafted SVG icons with an organic, nature-inspired aesthetic. Available in stroke and fill variants.',
    short_desc: '48 hand-crafted SVG icons — stroke and fill variants.',
    category: 'icon',
    price_cents: 0,
    is_free: true,
    cover_url: 'https://images.unsplash.com/photo-1553356084-58ef4a67b2a7?w=800&q=80',
    file_count: 2,
    published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'The Indie Creator Handbook',
    slug: 'indie-creator-handbook',
    description: 'A practical guide to building and monetizing digital products as a solo creator. Covers pricing, distribution, marketing, and building an audience from scratch.',
    short_desc: 'Practical guide to building digital products solo.',
    category: 'ebook',
    price_cents: 1200,
    is_free: false,
    cover_url: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80',
    file_count: 1,
    published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'Notion OS Dashboard',
    slug: 'notion-os-dashboard',
    description: 'A complete second-brain Notion template with project management, habit tracking, reading list, and weekly review systems.',
    short_desc: 'Complete Notion second-brain and productivity template.',
    category: 'template',
    price_cents: 800,
    is_free: false,
    cover_url: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&q=80',
    file_count: 1,
    published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'Figma Variables Starter',
    slug: 'figma-variables-starter',
    description: 'A free Figma file with a complete design token setup using Figma Variables. Includes light/dark mode, semantic color system, and typography scale.',
    short_desc: 'Free Figma Variables template with semantic tokens.',
    category: 'design',
    price_cents: 0,
    is_free: true,
    cover_url: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80',
    file_count: 1,
    published: true,
    created_at: new Date().toISOString(),
  },
]
