import type { ShowcasePost } from '@/types'

function hoursAgo(h: number) { return new Date(Date.now() - h * 3600000).toISOString() }

const IMGS = [
  'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=600&q=80',
  'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&q=80',
  'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=600&q=80',
  'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&q=80',
  'https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=600&q=80',
  'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&q=80',
  'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&q=80',
  'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
  'https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=600&q=80',
  'https://images.unsplash.com/photo-1545665277-5937489579f2?w=600&q=80',
  'https://images.unsplash.com/photo-1618004912476-29818d81ae2e?w=600&q=80',
  'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=600&q=80',
]

function creator(id: string, username: string, displayName: string) {
  return { id, user_id: `u${id}`, username, display_name: displayName, bio: null, avatar_url: null, website: null, twitter: null, total_products: 0, total_sales: 0, created_at: '' }
}

const CREATORS = [
  creator('c1',  'elena-design',  'Elena Vasquez'),
  creator('c2',  'kai-dev',       'Kai Nakamura'),
  creator('c3',  'sam-ux',        'Sam Torres'),
  creator('c4',  'mira-design',   'Mira Chen'),
  creator('c5',  'noah-framer',   'Noah Eriksson'),
  creator('c6',  'pia-writes',    'Pia Lindqvist'),
  creator('c7',  'leo-video',     'Leo Osei'),
  creator('c8',  'zoe-webflow',   'Zoe Fischer'),
  creator('c9',  'finn-audio',    'Finn Walsh'),
  creator('c10', 'ravi-writes',   'Ravi Patel'),
]

interface Def { caption: string; tags: string[]; cIdx: number; likes: number; dims: [number,number] }

const DEFS: Def[] = [
  { caption:'New brand identity for a fintech startup. Explored organic shapes to balance the corporate feel.', tags:['branding','logo-design','fintech'], cIdx:0, likes:24, dims:[600,450] },
  { caption:'Built a custom drag-and-drop kanban board with React DnD. Smooth animations and accessible keyboard nav.', tags:['react','frontend','open-source'], cIdx:1, likes:42, dims:[600,400] },
  { caption:'Dashboard redesign for a developer tools company. Focus on information density without sacrificing clarity.', tags:['ui-design','dashboard','dev-tools'], cIdx:2, likes:18, dims:[600,380] },
  { caption:'Illustration series for a meditation app. Watercolour textures on a digital canvas.', tags:['illustration','app-design','wellness'], cIdx:0, likes:37, dims:[600,600] },
  { caption:'Terminal-based portfolio website. Built with Next.js, renders as an interactive CLI.', tags:['frontend','nextjs','creative-coding'], cIdx:1, likes:56, dims:[600,340] },
  { caption:'Mobile app concept for a plant care tracker. Soft greens, playful micro-interactions.', tags:['mobile','ui-design','concept'], cIdx:2, likes:29, dims:[600,500] },
  { caption:'Wordmark exploration for an indie music label. Seven directions, two survivors.', tags:['branding','typography','music'], cIdx:3, likes:31, dims:[600,420] },
  { caption:'Framer site for a SaaS pricing page redesign. Scroll-linked animations, no JS.', tags:['framer','no-code','saas'], cIdx:4, likes:48, dims:[600,360] },
  { caption:'Character illustration pack for a kids learning app — 12 scenes, flat style.', tags:['illustration','kids','app-design'], cIdx:0, likes:62, dims:[600,600] },
  { caption:'Open-source data table component built with TanStack Table and shadcn/ui.', tags:['react','open-source','ui-design'], cIdx:1, likes:77, dims:[600,420] },
  { caption:'Onboarding flow redesign for a B2B platform. Cut steps from 9 to 4, conversion up 18%.', tags:['ux','onboarding','b2b'], cIdx:2, likes:34, dims:[600,480] },
  { caption:'Icon set for a productivity app — 80 icons, 3 weights, full Figma component set.', tags:['icons','figma','productivity'], cIdx:3, likes:45, dims:[600,400] },
  { caption:'Webflow site built from a Figma handoff. CMS blog, parallax header, 95 Lighthouse score.', tags:['webflow','design-to-code','blog'], cIdx:7, likes:22, dims:[600,340] },
  { caption:'Motion brand guide for a fintech startup. Easing curves, duration scale, and key transitions.', tags:['motion-design','branding','fintech'], cIdx:4, likes:53, dims:[600,450] },
  { caption:'Dark-mode email template system — 20 templates, React Email, fully responsive.', tags:['email','design-systems','react'], cIdx:1, likes:38, dims:[600,380] },
  { caption:'Landing page for a TypeScript course. Converted 2x better than the previous design.', tags:['landing-page','education','conversion'], cIdx:3, likes:41, dims:[600,520] },
  { caption:'Sound branding demo for a podcast network — three ident options, full rationale.', tags:['audio-branding','podcast','sound-design'], cIdx:8, likes:19, dims:[600,340] },
  { caption:'Notion OS template — my full personal operating system after 3 years of iteration.', tags:['notion','productivity','templates'], cIdx:9, likes:88, dims:[600,480] },
  { caption:'Colour system design for a multi-product company. 14 semantic tokens, light + dark.', tags:['design-systems','colour','tokens'], cIdx:2, likes:33, dims:[600,400] },
  { caption:'CLI tool for scaffolding Next.js projects — built with TypeScript and Ink.', tags:['cli','open-source','nextjs'], cIdx:1, likes:64, dims:[600,360] },
  { caption:'Photographic identity system for a sustainable fashion brand.', tags:['photography','branding','fashion'], cIdx:0, likes:29, dims:[600,600] },
  { caption:'Shopify theme build — custom sections, metafields, 98 Lighthouse performance score.', tags:['shopify','e-commerce','frontend'], cIdx:7, likes:35, dims:[600,420] },
  { caption:'Editorial layout exploration for a design magazine. Thinking about type-led design.', tags:['editorial','typography','print'], cIdx:3, likes:47, dims:[600,440] },
  { caption:'3D product mockup generator built in Three.js and React. Drag to rotate, click to export.', tags:['3d','react','creative-coding'], cIdx:4, likes:72, dims:[600,380] },
  { caption:'Podcast cover art suite — 8 shows, consistent brand family, all illustrated by hand.', tags:['illustration','podcast','branding'], cIdx:8, likes:26, dims:[600,600] },
  { caption:'Open-source chart library built with D3 and React. 12 chart types, dark mode.', tags:['data-viz','open-source','react'], cIdx:1, likes:59, dims:[600,400] },
  { caption:'Figma component documentation template — my workflow for annotating component APIs.', tags:['figma','design-systems','documentation'], cIdx:2, likes:44, dims:[600,340] },
  { caption:'Visual identity for an indie dev studio. Logo, wordmark, and a small icon family.', tags:['branding','logo-design','dev-studio'], cIdx:3, likes:31, dims:[600,480] },
  { caption:'Webflow e-commerce build for a ceramics artist. Product photography direction included.', tags:['webflow','e-commerce','photography'], cIdx:7, likes:23, dims:[600,400] },
  { caption:'Tab component with scroll-linked ink indicator — pure CSS, no JavaScript.', tags:['css','frontend','creative-coding'], cIdx:1, likes:91, dims:[600,360] },
  { caption:'Conference talk slide deck — 42 slides on design token architecture.', tags:['design-systems','talks','typography'], cIdx:0, likes:38, dims:[600,450] },
  { caption:'App icon for an iOS journaling app — three directions explored, one shipped.', tags:['app-icon','ios','branding'], cIdx:3, likes:54, dims:[600,600] },
  { caption:'Custom cursor and scroll interactions for a portfolio site. Built in vanilla JS.', tags:['interaction-design','javascript','portfolio'], cIdx:4, likes:67, dims:[600,380] },
  { caption:'Music video motion graphics for an independent artist. AE, no plugins.', tags:['motion-design','music','after-effects'], cIdx:6, likes:43, dims:[600,340] },
  { caption:'Rebranding a 10-year-old dev tool. Kept the legacy, modernised the mark.', tags:['branding','rebrand','dev-tools'], cIdx:0, likes:36, dims:[600,480] },
  { caption:'SaaS pricing page A/B test — the variant that lifted upgrades by 22%.', tags:['saas','conversion','ux'], cIdx:2, likes:81, dims:[600,400] },
  { caption:'iOS widget design for a habit tracker app. SwiftUI previews in the pitch.', tags:['ios','mobile','widgets'], cIdx:3, likes:49, dims:[600,360] },
  { caption:'Data visualisation dashboard built with Recharts and Next.js.', tags:['data-viz','nextjs','dashboard'], cIdx:1, likes:57, dims:[600,420] },
  { caption:'Illustrated map of a fictional world for a tabletop game. 40+ hours, Procreate.', tags:['illustration','game-design','procreate'], cIdx:0, likes:103, dims:[600,600] },
  { caption:'Framer micro-animation library — 30 reusable presets for common UI patterns.', tags:['framer','motion-design','components'], cIdx:4, likes:66, dims:[600,380] },
  { caption:'Brand guidelines PDF template — 24 pages, all Figma, fully editable.', tags:['branding','figma','templates'], cIdx:2, likes:41, dims:[600,440] },
  { caption:'Shopify product page rebuild — focus on reducing decision fatigue, AOV up 12%.', tags:['shopify','ux','e-commerce'], cIdx:7, likes:28, dims:[600,400] },
  { caption:'Monoline icon pack — 120 icons for a productivity SaaS. Consistent optical weight.', tags:['icons','design-systems','productivity'], cIdx:3, likes:37, dims:[600,360] },
  { caption:'Custom audio visualiser built with Web Audio API and Canvas.', tags:['creative-coding','audio','javascript'], cIdx:8, likes:52, dims:[600,340] },
  { caption:'Figma-to-React conversion at scale — 15 components, design token integration.', tags:['figma','react','design-systems'], cIdx:1, likes:44, dims:[600,420] },
  { caption:'Book cover series for a self-published author — 4 volumes, consistent family.', tags:['book-design','illustration','branding'], cIdx:0, likes:30, dims:[600,480] },
  { caption:'Real-time collaboration feature built with Yjs and WebSockets. Demo in the thread.', tags:['react','real-time','open-source'], cIdx:1, likes:75, dims:[600,400] },
  { caption:'Google Analytics 4 dashboard — rebuilt in Metabase with custom SQL.', tags:['data-viz','analytics','sql'], cIdx:9, likes:22, dims:[600,360] },
  { caption:'Logo animation for a SaaS product — three approaches, all under 2 seconds.', tags:['motion-design','branding','lottie'], cIdx:4, likes:48, dims:[600,340] },
  { caption:'Dark-mode illustration set for an API docs site — 8 hero images, SVG.', tags:['illustration','dark-mode','documentation'], cIdx:0, likes:61, dims:[600,600] },
  { caption:'Type-only poster series exploring negative space. Personal project.', tags:['typography','poster-design','personal'], cIdx:3, likes:39, dims:[600,480] },
  { caption:'Supabase + Next.js starter with full auth, RLS, and storage. Open source.', tags:['nextjs','supabase','open-source'], cIdx:1, likes:94, dims:[600,400] },
  { caption:'Newsletter redesign — improved open rate from 22% to 31% over 6 issues.', tags:['email','content','design'], cIdx:5, likes:27, dims:[600,360] },
  { caption:'Accessibility annotation kit for Figma — free download, 200+ annotations.', tags:['accessibility','figma','design-systems'], cIdx:2, likes:86, dims:[600,420] },
  { caption:'Webflow blog with CMS — live site built in 3 days, custom code cells.', tags:['webflow','blog','cms'], cIdx:7, likes:33, dims:[600,380] },
  { caption:'React drag-and-drop form builder — open source, TypeScript, Zod validation.', tags:['react','forms','open-source'], cIdx:1, likes:69, dims:[600,400] },
  { caption:'Product photography direction for a hardware startup. Remote brief, 3 rounds.', tags:['photography','product-design','hardware'], cIdx:0, likes:25, dims:[600,480] },
  { caption:'Personal site redesign — Astro, MDX, full dark mode, 99 Lighthouse performance.', tags:['astro','portfolio','frontend'], cIdx:4, likes:78, dims:[600,360] },
  { caption:'Music production template pack for Logic Pro — 12 genre templates.', tags:['audio','music-production','templates'], cIdx:8, likes:44, dims:[600,340] },
  { caption:'Glyph design exploration — custom ligatures for a monospace display typeface.', tags:['type-design','typography','personal'], cIdx:3, likes:57, dims:[600,500] },
  { caption:'CSS scroll-driven animation showcase — 8 patterns, all spec-compliant.', tags:['css','animation','creative-coding'], cIdx:1, likes:112, dims:[600,380] },
]

export const mockShowcase: ShowcasePost[] = DEFS.map((d, i) => ({
  id: `sh${i + 1}`,
  creator_id: CREATORS[d.cIdx].id,
  caption: d.caption,
  tags: d.tags,
  published: true,
  created_at: hoursAgo((i + 1) * 3),
  media: [{
    id: `m${i + 1}`,
    post_id: `sh${i + 1}`,
    media_url: IMGS[i % IMGS.length],
    media_type: 'image' as const,
    width: d.dims[0],
    height: d.dims[1],
    sort_order: 0,
  }],
  creator: CREATORS[d.cIdx],
  like_count: d.likes,
  liked_by_user: false,
}))
